name: CI

on:
    push:
        branches: ['main', 'develop']
    pull_request:
        branches: ['main', 'develop']
jobs:
    dev-check:
        if: contains(fromJson('["refs/heads/develop"]'), github.ref)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm i
            - name: Execute tests
              run: npm run test

    prod-check:
        if: contains(fromJson('["refs/heads/main"]'), github.ref)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm i
            - name: Execute tests
              run: npm run test
            - name: Upload coverage do codecov
              run: |
                  curl -Os https://uploader.codecov.io/latest/linux/codecov
                  chmod +x codecov
                  ./codecov -t ${{secrets.CODECOV_TOKEN}}
